### PR TITLE
Add the Scala extension

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
[test]

**Comment by gsmet** [comment]
@gastaldi looks like I still have the same issue and I'm not really in the white list. Could you have another look?

(I can force the merge as I have validated the commit on staging but I always prefer to have CI running)

**Comment by maorfr** [comment]
[test]

**Comment by gsmet** [comment]
@maorfr thanks!

**Comment by maorfr** [comment]
As a Red Hatter, you should add yourself to app-interface if you havn't already. Folks on #sd-app-sre on the coreos slack can help.

**Pull request merged**
